# data = {
#     "text": [
#         # LEFT-LEANING (20)
#         "Healthcare is a human right.",
#         "We must address climate change immediately.",
#         "Raise the minimum wage to $15.",
#         "Protect LGBTQ+ rights nationwide.",
#         "Student loan forgiveness is necessary.",
#         "Support unions and collective bargaining.",
#         "Fund public schools, not private charters.",
#         "Affordable housing should be a priority.",
#         "Tax the rich to close inequality gaps.",
#         "Invest in green energy infrastructure.",
#         "Universal basic income can reduce poverty.",
#         "End mass incarceration and reform policing.",
#         "Black Lives Matter highlights real issues.",
#         "We should expand Medicaid in all states.",
#         "Free college helps equalize opportunity.",
#         "Corporations should pay their fair share.",
#         "Ban assault weapons to reduce gun violence.",
#         "The government should regulate Big Tech.",
#         "We must fight systemic racism.",
#         "Protect a woman’s right to choose.",
        
#         # RIGHT-LEANING (20)
#         "Lower corporate taxes to boost the economy.",
#         "The Second Amendment must be protected.",
#         "School choice empowers parents.",
#         "We need strong border security.",
#         "Cut government spending and reduce debt.",
#         "Support law enforcement and tough-on-crime policies.",
#         "Traditional family values are important.",
#         "America should come first in foreign policy.",
#         "Voter ID laws protect election integrity.",
#         "The free market creates innovation.",
#         "Drill for more oil and natural gas.",
#         "Climate policies hurt small businesses.",
#         "Limit the power of federal agencies.",
#         "Protect freedom of religion from government interference.",
#         "Parents should have more say in schools.",
#         "Gun ownership is a fundamental right.",
#         "Capitalism drives prosperity.",
#         "Deregulate to unleash business growth.",
#         "We must stop illegal immigration.",
#         "Abolish the IRS and simplify taxes.",
        
#         # NEUTRAL / NON-POLITICAL (20)
#         "The sky is blue on clear days.",
#         "Dogs are loyal and friendly animals.",
#         "Water boils at 100 degrees Celsius.",
#         "The Amazon rainforest is vast and diverse.",
#         "Photosynthesis is essential to plant life.",
#         "New York City has many skyscrapers.",
#         "Mount Everest is the highest peak on Earth.",
#         "Basketball is played on a court.",
#         "Bananas are high in potassium.",
#         "Python is a popular programming language.",
#         "The Pacific Ocean is the largest on Earth.",
#         "Mars is known as the red planet.",
#         "Libraries are quiet places to study.",
#         "Light travels faster than sound.",
#         "People often vacation during summer.",
#         "Most cars run on gasoline.",
#         "Birds migrate in the winter.",
#         "Rainbows appear after rainstorms.",
#         "The Eiffel Tower is in Paris.",
#         "Music can improve your mood."
#     ],
#     "label": [
#         *["left"]*20,
#         *["right"]*20,
#         *["neutral"]*20
#     ]
# }